repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-format
        args: [--diff]
        additional_dependencies: []
        files: ^src/|^tests/
      - id: ruff
        args: []
        additional_dependencies: []
        files: ^src/|^tests/
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [--diff]
        additional_dependencies: []
        files: ^src/|^tests/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        args: []
        additional_dependencies: []
        files: ^src/
