[project]
name = "spo"
version = "0.1.0"
description = "A Python application that synchronizes Spotify playlists with YouTube Music"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru>=0.7.3",
    "python-dotenv>=1.1.0",
    "requests[security]>=2.32.4",
    "spotipy>=2.25.1"
]

[dependency-groups]
dev = [
    "coveralls>=4.0.1",
    "mypy>=1.16.1",
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
src-root = "src"

[project.scripts]
spo = "src.spo.main:main"

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
mypy_path = ["src"]
packages = ["spo"]
warn_unused_ignores = true
strict_optional = true
ignore_missing_imports = true

[tool.ruff]
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]
ignore = ["E501"]
[tool.ruff.lint.isort]

[tool.isort]
profile = "black"
src_paths = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = ["--strict-markers", "--strict-config", "--verbose"]
filterwarnings = ["error", "ignore::UserWarning", "ignore::DeprecationWarning"]
markers = [
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests"
]
