[project]
name = "spo"
version = "0.1.0"
description = "A Python application that synchronizes Spotify playlists with YouTube Music"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["python-dotenv>=1.0.1", "spotipy>=2.25.0"]

[dependency-groups]
dev = ["isort>=6.0.1", "mypy>=1.16.1", "pytest>=8.4.1", "ruff>=0.9.6"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project.scripts]
spo = "src.spo.main:main"

[tool.mypy]
python_version = "3.13"
mypy_path = "src"
packages = ["spo"]

[tool.ruff]
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W"]
ignore = ["E501"]

[tool.isort]
profile = "black"
src_paths = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = ["--strict-markers", "--strict-config", "--verbose"]
filterwarnings = ["error", "ignore::UserWarning", "ignore::DeprecationWarning"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests"
]
