name: Lint and Format Check

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.local/share/uv
          key: ${{ runner.os }}-python-${{ matrix.python-version }}-uv-lint-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-python-${{ matrix.python-version }}-uv-lint-
            ${{ runner.os }}-python-${{ matrix.python-version }}-uv-
            ${{ runner.os }}-python-${{ matrix.python-version }}-

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python environment
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Check code formatting with ruff
        run: |
          uv run ruff format --check --diff src tests

      - name: Run linting with ruff
        run: |
          uv run ruff check src tests

      - name: Check import sorting with isort
        run: |
          uv run isort --check-only --diff src tests

      - name: Run type checking with mypy
        run: |
          uv run mypy
